# Generated by Django 6.0.7 on 2026-07-30 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=64)),
                ('symptoms', models.JSONField(default=list)),
                ('age', models.PositiveIntegerField()),
                ('temperature', models.FloatField()),
                ('heart_rate', models.PositiveIntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('diagnosis', models.CharField(max_length=128)),
                ('confidence', models.FloatField()),
                ('urgency', models.CharField(max_length=20)),
                ('report', models.JSONField()),
                ('treatment_plan', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
